spring:
  datasource:
    url:                  ${USERS_DB:jdbc:postgresql://localhost:5432/users_db}
    username:             ${USERS_DB_USERNAME:user_service}
    password:             ${USERS_DB_PASSWORD:user_service_password}
  jpa:
    show-sql:             false
    open-in-view:         false
    properties:
      hibernate:
        format_sql:       false
        highlight_sql:    false
        use_sql_comments: false
  data:
    redis:
      host:               ${REDIS_HOST:localhost}
      port:               ${REDIS_PORT:6379}
  cache:
    type:                 redis
    redis:
      time-to-live:       10m
  output:
    ansi:
      enabled: always

decorator:
  datasource:
    datasource-proxy:
      logging:          slf4j
      query:
        enable-logging: false
      slow-query:
        enable-logging: true
      json-format:      false
      count-query:      true
      format-sql:       true
      multiline:        true

logging:
  level:
    org.hibernate.SQL:           off
    org.hibernate.orm.jdbc.bind: off
    net.ttddyy.dsproxy.listener: debug

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url:        ${USERS_DB:jdbc:postgresql://postgres:5432/users_db}
    username:   ${USERS_DB_USERNAME:user_service}
    password:   ${USERS_DB_PASSWORD:user_service_password}
  data:
    redis:
      host:     ${REDIS_HOST:redis}
      port:     ${REDIS_PORT:6379}
