spring:
  datasource:
    url: ${USERS_DB:jdbc:postgresql://localhost:5432/users_db}
    username: ${USERS_DB_USERNAME:user_service}
    password: ${USERS_DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  liquibase:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 10m
  output:
    ansi:
      enabled: always

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}
    issuer: authentication-service
    trusted-internal-service: authentication-service

decorator:
  datasource:
    enabled: true

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    net.ttddyy.dsproxy.listener: debug

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${USERS_DB:jdbc:postgresql://postgres:5432/users_db}
    username: ${USERS_DB_USERNAME:user_service}
    password: ${USERS_DB_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
