services:
  api-gateway:
    image: uglyraddan/ecommerce-restapi-api-gateway
    container_name: api-gateway
    environment:
      SERVER_PORT: 8080
      USER_SERVICE_URI: http://user-service:8081
      AUTH_SERVICE_URI: http://authentication-service:8082
      ORDER_SERVICE_URI: http://order-service:8083
      AUTH_SERVICE_BASE_URL: http://authentication-service:8082
    ports:
      - "8080:8080"
    depends_on:
      user-service:
        condition: service_started
      authentication-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - edge-network
      - internal-network

  user-service:
    image: uglyraddan/ecommerce-restapi-user-service
    container_name: user-service
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: docker
      USERS_DB_PASSWORD: ${USERS_DB_PASSWORD}
    expose:
      - "8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal-network

  authentication-service:
    image: uglyraddan/ecommerce-restapi-authentication-service
    container_name: authentication-service
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: docker
      IDENTITY_DB_PASSWORD: ${IDENTITY_DB_PASSWORD}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      USER_SERVICE_BASE_URL: http://user-service:8081
    expose:
      - "8082"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - internal-network

  order-service:
    image: uglyraddan/ecommerce-restapi-order-service
    container_name: order-service
    environment:
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: docker
      ORDERS_DB: ${ORDERS_DB}
      ORDERS_DB_PASSWORD: ${ORDERS_DB_PASSWORD}
      USER_SERVICE_BASE_URL: http://user-service:8081
      CURSOR_SECRET: ${CURSOR_SECRET}
    expose:
      - "8083"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - internal-network

  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/script/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - edge-network
      - internal-network

  redis:
    image: redis:8.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - edge-network
      - internal-network

volumes:
  postgres_data:
    driver: local

networks:
  edge-network:
    driver: bridge

  internal-network:
    driver: bridge
    internal: true
