apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: docker

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  USERS_DB: jdbc:postgresql://postgres:5432/users_db
  USERS_DB_USERNAME: user_service
  IDENTITY_DB: jdbc:postgresql://postgres:5432/identity_db
  IDENTITY_DB_USERNAME: authentication_service
  ORDERS_DB: jdbc:postgresql://postgres:5432/orders_db
  ORDERS_DB_USERNAME: order_service

  PAYMENTS_DB: mongodb://root:root@mongo:27017/payments?authSource=admin

  USER_SERVICE_URI: http://user-service:8081
  AUTH_SERVICE_URI: http://authentication-service:8082
  ORDER_SERVICE_URI: http://order-service:8083
  PAYMENT_SERVICE_URI: http://payment-service:8084

  USER_SERVICE_BASE_URL: http://user-service:8081
  ORDER_SERVICE_BASE_URL: http://order-service:8083
  PAYMENT_SERVICE_BASE_URL: http://payment-service:8084

  PAYMENTS_TOPIC_PARTITIONS: "1"
  PAYMENTS_TOPIC_REPLICAS: "1"
  PAYMENTS_TOPIC_MIN_ISR: "1"
  PAYMENTS_OUTBOX_BATCH_SIZE: "200"
  PAYMENTS_OUTBOX_POLL_DELAY_MS: "250"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: ecommerce
data:
  init.sql: |
    -- Users Database
    
    CREATE ROLE user_service
        WITH LOGIN
        PASSWORD 'user_service_password'
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE
        NOINHERIT;
    
    CREATE DATABASE users_db
        OWNER user_service;
    
    GRANT CONNECT ON DATABASE users_db TO user_service;
    
    \connect users_db
    
    GRANT USAGE, CREATE ON SCHEMA public TO user_service;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_service;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO user_service;
    
    -- Identity Database
    
    CREATE ROLE authentication_service
        WITH LOGIN
        PASSWORD 'authentication_service_password'
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE
        NOINHERIT;
    
    CREATE DATABASE identity_db
        OWNER authentication_service;
    
    GRANT CONNECT ON DATABASE identity_db TO authentication_service;
    
    \connect identity_db
    
    GRANT USAGE, CREATE ON SCHEMA public TO authentication_service;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authentication_service;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO authentication_service;
    
    -- Orders Database
    
    CREATE ROLE order_service
        WITH LOGIN
        PASSWORD 'order_service_password'
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE
        NOINHERIT;
    
    CREATE DATABASE orders_db
        OWNER order_service;
    
    GRANT CONNECT ON DATABASE orders_db TO order_service;
    
    \connect orders_db
    
    GRANT USAGE, CREATE ON SCHEMA public TO order_service;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO order_service;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO order_service;
