apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  USERS_DB_PASSWORD: user_service_password
  IDENTITY_DB_PASSWORD: authentication_service_password
  ORDERS_DB_PASSWORD: order_service_password

  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: root

  CURSOR_SECRET: placeholder
  RANDOM_ORG_API_KEY: placeholder

  JWT_PUBLIC_KEY: placeholder
  JWT_PRIVATE_KEY: placeholder
